### ISSUE TITLE
Error:(18, 8) error: RNSecureKeyStorePackage is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by LudovicE07** [pradeep1991singh/react-native-secure-key-store#11]
Hi,

I've got error with lasted version when I try to lunch my android App.
This is my error: 

`Error:(18, 8) error: RNSecureKeyStorePackage is not abstract and does not override abstract method createJSModules() in ReactPackage`

This is my package.json

> {
	"name": "Transfusion",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"moment": "^2.19.1",
		"prop-types": "^15.6.0",
		"react": "16.0.0",
		"react-native": "0.50.1",
		"react-moment": "^0.6.5",
		"react-native-camera": "^0.10.0",
		"react-native-elements": "^0.17.0",
		"react-native-event-listeners": "^1.0.3",
		"react-native-i18n": "^2.0.8",
		"react-native-phone-call": "^1.0.4",
		"react-native-secure-key-store": "^1.0.7",
		"react-native-splash-screen": "^3.0.1",
		"react-native-vector-icons": "^4.4.2",
		"react-navigation": "^1.0.0-beta.15"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0"
	},
	"jest": {
		"preset": "react-native"
	}
}

Do you have any idea?
Thanks for your help.

**Comment by LudovicE07** [comment]
Hi, i've try too to use react-native-secure-key-store ^1.0.8 and still has error.

Thanks you,

**Comment by pradeep1991singh** [comment]
@LudovicE07  hey, can you try with react-native-secure-key-store@1.0.6 and let me know if that works?

**Comment by LudovicE07** [comment]
Hi, thanks for your reply, I fix the error with totally new project and new npm install for each installed module. It's works with version 1.0.8.

Thanks you,
